# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'githubauth' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for githubauth

  # Utility
  pod 'Alamofire'
  pod 'RealmSwift'
  pod 'Nuke'

  # UI
  pod 'MaterialComponents/Dialogs'
  pod 'MaterialComponents/Ink'

  target 'githubauthTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
